### ISSUE TITLE
Gifs not supported in OpenCV

### ISSUE THREAD

**Issue by yummiecrossiant** [contourlineprinter/capstone#7]
It seems like gifs are not supported in OpenCV. i need to see if there's a way to resolve that.

**Comment by kennysexton** [comment]
It seems like .jpg and .png work well,  we also should probably test .tiff if we are going to try and get .gif to work

**Comment by kennysexton** [comment]
![image](https://user-images.githubusercontent.com/26152532/55750076-804cbc80-5a10-11e9-8192-b241654a3390.png)

We now pass the file names through a regex expression that checks for valid file types.  I took out .gif since it doesn't work at this time.  If you do get it working, then will will need to add back gif as part of the regex

**Comment by yummiecrossiant** [comment]
cool. now we don't have to worry about people uploading .gifs. i think .tiff should be ok as it is one of the supported formats on openCV (see link below) but i'll test it too whenever i get around to working on this issue.

https://docs.opencv.org/4.0.1/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56
